import matplotlib.pyplot as plt
import matplotlib.mlab as mlab

def plotParticles(v_e_para, v_e_perp, v_i_para, v_i_perp, z_e, z_i, B_z, E_z, B_E_z_dim):
    plt.figure(1)
    plt.plot(v_e_para, v_e_perp, '.')
    #plt.axis([-5,5,0.0,5])
    plt.title('Electrons')
    plt.xlabel('Vpara (Re / s)')
    plt.ylabel('Vperp (Re / s)')
    plt.savefig('electrons.png')

    plt.figure(2)
    plt.plot(v_i_para, v_i_perp, '.')
    #plt.axis([-0.3,0.7,0.0,0.4])
    plt.title('Ions')
    plt.xlabel('Vpara')
    plt.ylabel('Vperp')
    plt.savefig('ions.png')

    plt.figure(3)
    plt.plot(v_e_perp, z_e, '.')
    #plt.axis([-0.3,0.7,0.0,0.4])
    plt.title('Electrons')
    plt.xlabel('Vperp (Re / s)')
    plt.ylabel('Z (Re)')
    plt.savefig('z_vprp_electrons.png')
    
    plt.figure(4)
    plt.plot(v_i_perp, z_i, '.')
    #plt.axis([-0.3,0.7,0.0,0.4])
    plt.title('Ions')
    plt.xlabel('Vperp (Re / s)')
    plt.ylabel('Z (Re)')
    plt.savefig('z_vprp_ions.png')

    plt.figure(5)
    plt.plot(v_e_para, z_e, '.')
    #plt.axis([-0.3,0.7,0.0,0.4])
    plt.title('Electrons')
    plt.xlabel('Vpara (Re / s)')
    plt.ylabel('Z (Re)')
    plt.savefig('z_vpra_electrons.png')
    
    plt.figure(6)
    plt.plot(v_i_para, z_i, '.')
    #plt.axis([-0.3,0.7,0.0,0.4])
    plt.title('Ions')
    plt.xlabel('Vpara (Re / s)')
    plt.ylabel('Z (Re)')
    plt.savefig('z_vpra_ions.png')

    plt.figure(7)
    plt.plot(B_E_z_dim, B_z, '.')
    #plt.axis([-0.3,0.7,0.0,0.4])
    plt.title('B Field')
    plt.xlabel('Z (Re)')
    plt.ylabel('B (T)')
    plt.savefig('B(z).png')

    plt.figure(8)
    plt.plot(B_E_z_dim, E_z, '.')
    #plt.axis([-0.3,0.7,0.0,0.4])
    plt.title('E Field')
    plt.xlabel('Z (Re)')
    plt.ylabel('E (V/m)')
    plt.savefig('E(z).png')

    plt.show()